server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/news-portal
          jwk-set-uri: http://localhost:8080/realms/news-portal/protocol/openid-connect/certs

# 若保留本地檔案上傳，可在此配置上傳目錄
app:
  upload:
    directory: ./uploads # 本地儲存的路徑，可自行調整

cloud:
  aws:
    s3:
      # AWS S3 或 MinIO 相關設定
      bucket: news-media-bucket # 實際 bucket 名稱
      region: ap-northeast-1 # 實際 region，e.g. us-east-1, ap-northeast-1 等
      access-key: AWS_ACCESS_KEY # 請填入 AWS Access Key
      secret-key: AWS_SECRET_KEY # 請填入 AWS Secret Key

      # endpoint 若留空 (或不設) 表示使用 AWS 官方預設 Endpoint
      # 若使用 MinIO 或客製 Endpoint，請填寫
      endpoint: "" # e.g. "https://play.min.io" or "https://s3.ap-northeast-1.amazonaws.com"
