server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/news-portal
          jwk-set-uri: http://localhost:8080/realms/news-portal/protocol/openid-connect/certs
